%% Script info
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% File name: "CreateMapForTimePatch.m"                         %
% Purpose: Create a simple Map containers for the time patch   %
% value of the current data set.                               %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%

function mapForTimePatch = CreateMapForTimePatch()

keySet = {'32', '1a', '43', '2', '2a', '22', '5b', 'Db', 'f3', 'c3', '3'};
    valueSet = {'CreateDataVector32(Binary_Data, CurrentChannel, double(Range));', ...
        'CreateDataVector1a(Binary_Data, CurrentChannel, double(Range));', ...
        'CreateDataVector43(Binary_Data, CurrentChannel, double(Range));', ...
        'CreateDataVector2(Binary_Data, CurrentChannel, double(Range));', ...
        'CreateDataVector2a(Binary_Data, CurrentChannel, double(Range));', ...
        'CreateDataVector22(Binary_Data, CurrentChannel, double(Range));', ...
        'CreateDataVector5b(Binary_Data, CurrentChannel, double(Range));', ...
        'CreateDataVectorDb(Binary_Data, CurrentChannel, double(Range));', ...
        'CreateDataVectorf3(Binary_Data, CurrentChannel, double(Range));', ...
        'CreateDataVectorc3(Binary_Data, CurrentChannel, double(Range));', ...
        'CreateDataVector3(Binary_Data, CurrentChannel, double(Range));', ...
    };
% WHEN ADDING A NEW TIME PATCH DON'T FORGET TO UPDATE READLSTDATA AND THE
% RESPECTIVE CREATE DATA VECOTR FUNCTION
    mapForTimePatch = containers.Map(keySet, valueSet);
end